network = "mainnet"
client_release_channel = "testing"
client_release_version = "v0.200.0-rc8"
services_version = "test"
ethereum_amount_required = 2e16
routing_mode = "local"

[service_token]
ticker = "RDN"
amount_required = 6e18
swap_amount_1 = 10e18
swap_amount_2 = 20e18
swap_amount_3 = 50e18

[transfer_token]
ticker = "DAI"
amount_required = 2e18
swap_amount_1 = 2e18
swap_amount_2 = 5e18
swap_amount_3 = 10e18
